import {
  Bell,
  Columns2,
  Command,
  FilePlus,
  FolderOpen,
  FolderPlus,
  GitBranch,
  Languages,
  Monitor,
  Moon,
  PanelLeftClose,
  PanelLeftOpen,
  Rows2,
  Search,
  Settings,
  Sun,
  Terminal,
} from "lucide-solid";

export {
  Bell as BellIcon,
  Columns2 as SplitHorizontalIcon,
  Command as CommandIcon,
  FilePlus as FilePlusIcon,
  FolderOpen as FilesIcon,
  FolderPlus as FolderPlusIcon,
  GitBranch as ReviewIcon,
  Languages as LanguagesIcon,
  Monitor as MonitorIcon,
  Moon as MoonIcon,
  PanelLeftClose as PanelCloseIcon,
  PanelLeftOpen as PanelOpenIcon,
  Rows2 as SplitVerticalIcon,
  Search as SearchIcon,
  Settings as SettingsIcon,
  Sun as SunIcon,
  Terminal as TerminalIcon,
};
