import {
  Terminal,
  FolderOpen,
  GitBranch,
  Moon,
  Sun,
  Monitor,
  Bell,
  Languages,
  PanelLeftOpen,
  PanelLeftClose,
  Command,
  Settings,
  Search,
} from "lucide-solid";

export {
  Terminal as TerminalIcon,
  FolderOpen as FilesIcon,
  GitBranch as ReviewIcon,
  Moon as MoonIcon,
  Sun as SunIcon,
  Monitor as MonitorIcon,
  Bell as BellIcon,
  Languages as LanguagesIcon,
  PanelLeftOpen as PanelOpenIcon,
  PanelLeftClose as PanelCloseIcon,
  Command as CommandIcon,
  Settings as SettingsIcon,
  Search as SearchIcon,
};
